<a href="https://colab.research.google.com/github/DianaTorresV/Company_U_Analysis/blob/main/Project_Unicorn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Unicorn

## Part 0: Preparations

### Installing and importing packages

In [ ]:
import pandas as pd
import sqlalchemy as sa
pd.set_option('display.max_rows', 1000)

### Making a connection

In [ ]:
unicorn_url = 'postgresql://Test:bQNxVzJL4g6u@ep-noisy-flower-846766-pooler.us-east-2.aws.neon.tech/Unicorn?sslmode=require'

Remember: Connecting with SQLAlchemy always works in two steps:

1.   Create an engine
2.   Make a connection

In [ ]:
engine = sa.create_engine(unicorn_url)
connection = engine.connect().execution_options(isolation_level="AUTOCOMMIT")

### Schema

## Tasks:

In [ ]:
# 1. How many customers do we have in the data?
query = """
SELECT COUNT(DISTINCT customer_id)
FROM customers
;
"""

display(pd.read_sql(sa.text(query),connection))

   count
0    795

In [ ]:
# 2. What was the city with the most profit for the company in 2015?
query = """
SELECT shipping_city, SUM(order_profits) AS city_profits
FROM order_details od
JOIN orders o
ON o.order_id = od.order_id
WHERE EXTRACT(YEAR FROM o.order_date) = 2015
GROUP BY shipping_city
ORDER BY city_profits DESC
LIMIT 1
;
"""

display(pd.read_sql(sa.text(query),connection))

   shipping_city  city_profits
0  New York City       14753.0

In [ ]:
# 3. In 2015, what was the most profitable city's profit?
query = """
SELECT shipping_city, SUM(order_profits) AS city_profits
FROM order_details od
JOIN orders o
ON o.order_id = od.order_id
WHERE EXTRACT(YEAR FROM o.order_date) = 2015
GROUP BY shipping_city
ORDER BY city_profits DESC
LIMIT 1
;
"""

display(pd.read_sql(sa.text(query),connection))

   shipping_city  city_profits
0  New York City       14753.0

In [ ]:
# 4. How many different cities do we have in the data? Please refer just to the city name and not similar city names in different states


query = """
SELECT COUNT(DISTINCT shipping_city) AS num_city_names
FROM orders;
"""

display(pd.read_sql(sa.text(query),connection))

   num_city_names
0             531

In [ ]:
for i in range(1,6):
    for j in range(i):
        print(i,end="")
print()

122333444455555

In [ ]:
def reverse_number(number):
    # Your code here

       return (number % 10 * 10000) +(((number % 100) - (number % 10)) * 100) + ((((number % 1000) - (number % 100))) * 1) +(((number % 10000) - (number % 1000)) // 100) +(number // 10000)

print(reverse_number(12345))

54321

In [ ]:
2^2

0

In [ ]:
# 5. Show the total spent by customers from low to high.
query = """
SELECT
	c.customer_id AS customer_id,
	SUM(od.order_sales) AS total_sales
FROM customers c
	JOIN orders o
	on c.customer_id = o.customer_id
JOIN order_details od
	on o.order_id = od.order_id
GROUP BY c.customer_id
ORDER BY total_sales ASC
;
"""

display(pd.read_sql(sa.text(query),connection))

     customer_id  total_sales
0            456          5.0
1            738          5.0
2            546         16.0
3            124         17.0
4            657         22.0
5            626         48.0
6            725         49.0
7            448         50.0
8              9         58.0
9            355         72.0
10           292         81.0
11            38         88.0
12           419         89.0
13           649         98.0
14           169        113.0
15           248        125.0
16            95        131.0
17           613        133.0
18           310        147.0
19           529        154.0
20           229        157.0
21           605        160.0
22            54        161.0
23           550        162.0
24            51        170.0
25           383        195.0
26            26        201.0
27           333        219.0
28           642        221.0
29           316        227.0
30           270        228.0
31           315        237.0
32           594        239.0
33           666        243.0
34           318        251.0
35            34        264.0
36            98        266.0
37           237        269.0
38           571        274.0
39            72        274.0
40           719        278.0
41           722        281.0
42           162        287.0
43           449        288.0
44           371        305.0
45           361        310.0
46           467        318.0
47           104        321.0
48           450        330.0
49           235        343.0
50           324        359.0
51           279        367.0
52            20        367.0
53           481        368.0
54           521        370.0
55           564        377.0
56           787        381.0
57           354        384.0
58           400        386.0
59            71        386.0
60           495        400.0
61            99        415.0
62           705        418.0
63           785        427.0
64           701        432.0
65           750        439.0
66           437        449.0
67           443        454.0
68           269        462.0
69           395        471.0
70           174        475.0
71           501        476.0
72           700        478.0
73            37        496.0
74           637        528.0
75           387        529.0
76           123        538.0
77           163        551.0
78           128        565.0
79           565        571.0
80           109        583.0
81           221        585.0
82            16        586.0
83           488        594.0
84            65        600.0
85            96        605.0
86           620        615.0
87            64        629.0
88           502        640.0
89           131        641.0
90           477        644.0
91           399        644.0
92            56        649.0
93           118        658.0
94            44        658.0
95            84        659.0
96            22        662.0
97           754        676.0
98           262        684.0
99           606        689.0
100          403        696.0
101          362        710.0
102          585        730.0
103          603        730.0
104          331        738.0
105           39        738.0
106          636        740.0
107          586        741.0
108          535        742.0
109          767        742.0
110          338        744.0
111           66        744.0
112          239        756.0
113          471        757.0
114          716        759.0
115          670        764.0
116          551        774.0
117          525        777.0
118          322        785.0
119           85        791.0
120          508        795.0
121          209        798.0
122          105        809.0
123           24        813.0
124          745        816.0
125          265        827.0
126          756        834.0
127           42        835.0
128          144        844.0
129          784        846.0
130          779        847.0
131          531        855.0
132          406        858.0
133           59        862.0
134          379        864.0
135          376        865.0
136          629        878.0
137          319        884.0
138          665        884.0
139          141        885.0
140          663        886.0
141          329        887.0
142            1        887.0
143          394        901.0
144          704        902.0
145          135        906.0
146          426        909.0
147           17        914.0
148          499        922.0
149          278        925.0
150           28        926.0
151          263        934.0
152          510        936.0
153          261        944.0
154          655        947.0
155          120        950.0
156          617        955.0
157          352        955.0
158          393        959.0
159          724        966.0
160          654        968.0
161           10        969.0
162          661        971.0
163          755        974.0
164           70        983.0
165          439        984.0
166          780        994.0
167          116       1006.0
168          482       1007.0
169          621       1008.0
170          479       1009.0
171          689       1019.0
172          748       1024.0
173          543       1031.0
174          742       1038.0
175          272       1041.0
176          244       1042.0
177          726       1044.0
178          199       1051.0
179           25       1056.0
180           23       1056.0
181          358       1057.0
182          786       1057.0
183          612       1057.0
184          210       1059.0
185          599       1062.0
186          165       1076.0
187          212       1079.0
188          223       1081.0
189          365       1082.0
190          682       1085.0
191          369       1092.0
192          764       1095.0
193           11       1114.0
194          202       1122.0
195          378       1130.0
196          653       1137.0
197          126       1138.0
198          444       1145.0
199          167       1148.0
200          243       1156.0
201          377       1157.0
202           29       1172.0
203          218       1175.0
204           82       1181.0
205          277       1187.0
206          523       1203.0
207          238       1205.0
208          151       1206.0
209          341       1215.0
210          266       1220.0
211          588       1220.0
212          578       1229.0
213          524       1241.0
214          763       1245.0
215          256       1245.0
216          396       1245.0
217          507       1253.0
218          711       1255.0
219          299       1255.0
220          533       1257.0
221          474       1259.0
222          125       1262.0
223          242       1267.0
224          720       1271.0
225          597       1278.0
226          122       1279.0
227          303       1285.0
228          228       1298.0
229          317       1299.0
230          175       1300.0
231          252       1302.0
232          504       1304.0
233          702       1306.0
234          483       1315.0
235          699       1319.0
236          196       1321.0
237          537       1321.0
238          675       1324.0
239           67       1336.0
240          119       1338.0
241          680       1341.0
242          512       1342.0
243          470       1347.0
244          677       1348.0
245          298       1362.0
246          234       1378.0
247          283       1383.0
248          771       1387.0
249          364       1388.0
250          561       1397.0
251          187       1397.0
252          314       1400.0
253          595       1405.0
254          372       1418.0
255          553       1420.0
256          647       1420.0
257          153       1423.0
258          404       1428.0
259          538       1429.0
260          747       1429.0
261          732       1435.0
262          593       1441.0
263          624       1453.0
264           35       1455.0
265          609       1457.0
266          220       1458.0
267          619       1460.0
268          101       1460.0
269          584       1467.0
270          453       1469.0
271          736       1470.0
272          145       1475.0
273          793       1494.0
274          190       1504.0
275          386       1507.0
276           40       1515.0
277          434       1520.0
278           83       1522.0
279          115       1527.0
280          137       1537.0
281          108       1539.0
282          486       1547.0
283          498       1561.0
284          580       1567.0
285          420       1568.0
286          301       1569.0
287          344       1571.0
288          541       1582.0
289          183       1583.0
290           81       1586.0
291           13       1588.0
292          181       1600.0
293          749       1603.0
294          513       1611.0
295           50       1624.0
296           48       1639.0
297          264       1644.0
298          164       1659.0
299          140       1662.0
300          363       1669.0
301          121       1676.0
302          136       1679.0
303          519       1686.0
304          427       1686.0
305          662       1686.0
306          198       1687.0
307           77       1698.0
308          408       1706.0
309          770       1707.0
310          226       1712.0
311           97       1728.0
312          368       1733.0
313          545       1736.0
314          778       1736.0
315            8       1736.0
316           80       1738.0
317          476       1740.0
318            2       1744.0
319          549       1759.0
320          201       1762.0
321          139       1771.0
322          359       1791.0
323           32       1792.0
324          350       1804.0
325          574       1822.0
326          600       1823.0
327          582       1832.0
328          259       1833.0
329           63       1839.0
330          591       1841.0
331          703       1861.0
332          185       1861.0
333          556       1871.0
334          113       1873.0
335          709       1873.0
336          695       1875.0
337          468       1880.0
338          697       1885.0
339          305       1888.0
340          422       1889.0
341          728       1903.0
342          514       1908.0
343          356       1912.0
344          351       1934.0
345          769       1937.0
346          160       1949.0
347          466       1963.0
348          684       1966.0
349          576       1974.0
350          592       1988.0
351          240       1989.0
352          320       1991.0
353          781       2006.0
354          227       2012.0
355          572       2031.0
356          127       2035.0
357           58       2052.0
358          761       2054.0
359          475       2060.0
360          646       2068.0
361          516       2071.0
362          774       2074.0
363          639       2086.0
364          708       2096.0
365          469       2096.0
366          416       2122.0
367          245       2139.0
368          171       2149.0
369          385       2153.0
370          247       2161.0
371          743       2162.0
372          567       2163.0
373          326       2163.0
374          656       2169.0
375          429       2171.0
376          193       2172.0
377          692       2180.0
378          583       2182.0
379           93       2188.0
380          306       2190.0
381          751       2198.0
382          251       2200.0
383          413       2202.0
384          518       2203.0
385          348       2204.0
386          614       2207.0
387          206       2215.0
388          560       2219.0
389          539       2220.0
390          309       2222.0
391           27       2235.0
392          454       2239.0
393          353       2241.0
394          765       2243.0
395          440       2245.0
396          491       2255.0
397          411       2257.0
398          506       2258.0
399          414       2261.0
400           94       2262.0
401          177       2271.0
402          289       2273.0
403          345       2280.0
404          446       2280.0
405          459       2298.0
406          526       2302.0
407          148       2306.0
408          213       2333.0
409          254       2340.0
410          648       2342.0
411          511       2351.0
412          179       2354.0
413           33       2356.0
414          340       2358.0
415          569       2368.0
416          360       2371.0
417          172       2372.0
418          186       2372.0
419          789       2375.0
420          208       2391.0
421          485       2393.0
422          739       2423.0
423          505       2427.0
424           73       2442.0
425          532       2453.0
426          777       2454.0
427          302       2454.0
428          106       2455.0
429          496       2456.0
430          280       2456.0
431          555       2461.0
432           86       2472.0
433          142       2473.0
434          457       2477.0
435          528       2477.0
436          570       2487.0
437          590       2494.0
438           31       2495.0
439          233       2502.0
440          402       2518.0
441          401       2519.0
442          291       2523.0
443          143       2533.0
444          332       2534.0
445           41       2538.0
446          173       2541.0
447          216       2551.0
448          117       2564.0
449          500       2565.0
450          253       2567.0
451           87       2568.0
452          566       2576.0
453          712       2578.0
454           18       2584.0
455          327       2586.0
456          710       2596.0
457          688       2603.0
458          425       2618.0
459          618       2619.0
460          150       2649.0
461          205       2652.0
462          276       2657.0
463          628       2663.0
464          573       2673.0
465          286       2681.0
466           90       2682.0
467          102       2684.0
468          410       2698.0
469          357       2710.0
470          492       2723.0
471          389       2726.0
472          484       2727.0
473          455       2740.0
474          438       2745.0
475          536       2752.0
476          149       2757.0
477          257       2768.0
478          610       2770.0
479          384       2773.0
480          643       2787.0
481          773       2798.0
482           69       2799.0
483          293       2819.0
484          772       2820.0
485          152       2832.0
486          412       2834.0
487          197       2840.0
488          462       2845.0
489          268       2846.0
490          178       2854.0
491          161       2869.0
492          336       2872.0
493          598       2875.0
494          211       2882.0
495           68       2889.0
496          520       2890.0
497          563       2894.0
498          182       2900.0
499          638       2913.0
500          493       2922.0
501          696       2922.0
502          407       2933.0
503           75       2934.0
504          473       2935.0
505          740       2942.0
506          154       2946.0
507          733       2955.0
508          575       2966.0
509          207       2974.0
510          281       2984.0
511          534       2986.0
512          464       2989.0
513          129       3038.0
514          184       3040.0
515            3       3051.0
516          676       3053.0
517          693       3056.0
518          430       3058.0
519          753       3059.0
520          542       3062.0
521          273       3073.0
522          296       3078.0
523          274       3084.0
524          587       3088.0
525          423       3102.0
526          706       3126.0
527          713       3128.0
528          735       3129.0
529          659       3134.0
530          517       3146.0
531          415       3152.0
532          146       3154.0
533          349       3158.0
534          366       3175.0
535          219       3195.0
536          112       3197.0
537          156       3201.0
538          497       3207.0
539           19       3215.0
540          627       3221.0
541          465       3232.0
542          694       3234.0
543          249       3236.0
544          132       3241.0
545          463       3247.0
546          330       3250.0
547            5       3251.0
548            6       3255.0
549          188       3256.0
550          342       3257.0
551          194       3274.0
552          641       3280.0
553          111       3288.0
554          107       3288.0
555          634       3301.0
556          622       3310.0
557          421       3313.0
558          224       3318.0
559           61       3324.0
560          189       3336.0
561          730       3338.0
562          230       3343.0
563          241       3357.0
564          782       3361.0
565          667       3364.0
566          775       3368.0
567          671       3406.0
568          664       3408.0
569          282       3419.0
570          679       3424.0
571          601       3454.0
572          258       3487.0
573           45       3489.0
574          645       3495.0
575          267       3511.0
576          232       3540.0
577          295       3583.0
578          744       3589.0
579          632       3622.0
580          668       3628.0
581          674       3630.0
582          367       3638.0
583          246       3643.0
584          159       3651.0
585          472       3654.0
586           79       3676.0
587          334       3690.0
588          683       3732.0
589          285       3737.0
590          405       3748.0
591          374       3762.0
592          489       3766.0
593          509       3785.0
594          130       3789.0
595          527       3793.0
596          522       3805.0
597          651       3816.0
598          581       3819.0
599           49       3831.0
600          658       3832.0
601          391       3868.0
602           92       3888.0
603          288       3890.0
604          435       3908.0
605          577       3909.0
606          236       3909.0
607          147       3914.0
608          441       3920.0
609          615       3922.0
610          300       3922.0
611          478       3931.0
612          686       3980.0
613          530       3984.0
614          180       3985.0
615          727       3990.0
616          287       4047.0
617          311       4073.0
618          222       4074.0
619          718       4106.0
620          608       4115.0
621          552       4151.0
622          650       4160.0
623          294       4172.0
624          370       4198.0
625           89       4205.0
626          768       4234.0
627          168       4247.0
628          284       4257.0
629           15       4262.0
630          752       4266.0
631          631       4272.0
632          192       4283.0
633          723       4283.0
634          503       4300.0
635          557       4329.0
636          715       4345.0
637          297       4355.0
638          255       4358.0
639          681       4374.0
640           57       4376.0
641          100       4410.0
642          428       4418.0
643          346       4427.0
644          494       4433.0
645          741       4456.0
646          461       4492.0
647          717       4494.0
648           53       4501.0
649           60       4511.0
650           55       4523.0
651          203       4532.0
652          275       4589.0
653          669       4626.0
654          431       4642.0
655          217       4655.0
656          271       4657.0
657          452       4705.0
658          630       4714.0
659          304       4717.0
660          766       4737.0
661           74       4752.0
662          375       4762.0
663          721       4767.0
664          660       4794.0

In [ ]:
# 6. What is the most profitable city in the State of Tennessee?
query = """
SELECT shipping_city
FROM orders join order_details USING(order_id)
WHERE shipping_state = 'Tennessee'
GROUP BY shipping_city
ORDER BY SUM(order_profits) DESC
LIMIT 1
"""

display(pd.read_sql(sa.text(query),connection))

  shipping_city
0       Lebanon

In [ ]:
# 7. What’s the average annual profit for that city across all years?

query = """
SELECT AVG(order_profits) AS avg_annual_profit_Lebanon
FROM orders
JOIN order_details
USING (order_id)
WHERE shipping_city='Lebanon' AND shipping_state='Tennessee'

"""

display(pd.read_sql(sa.text(query),connection))

   avg_annual_profit_lebanon
0                  27.666667

In [ ]:
# 8. What is the distribution of customer types in the data?
query = """
SELECT
customer_segment,
COUNT(customer_id)
FROM customers
GROUP BY customer_segment
"""

display(pd.read_sql(sa.text(query),connection))

  customer_segment  count
0         Consumer    410
1        Corporate    237
2      Home Office    148

In [ ]:
# 9. What’s the most profitable product category on average in Iowa across all years?
query = """
SELECT DISTINCT product_category,
AVG(order_profits) AS avg_most_profitable
FROM product p
JOIN order_details od ON p.product_id=od.product_id
JOIN orders o ON o.order_id=od.order_id
WHERE shipping_state = 'Iowa'
GROUP BY product_category
ORDER BY avg_most_profitable desc
LIMIT 1
"""

display(pd.read_sql(sa.text(query),connection))

  product_category  avg_most_profitable
0        Furniture               130.25

In [ ]:
# 10. What is the most popular product in that category across all states in 2016?

query = """
SELECT product_name, SUM(quantity) AS quantity_product_sold
FROM orders o
JOIN order_details od
USING (order_id)
JOIN product p
USING(product_id)
WHERE product_category='Furniture' AND EXTRACT(YEAR FROM order_date)::Integer=2016
GROUP BY product_name
ORDER BY quantity_product_sold DESC
LIMIT 1
"""

display(pd.read_sql(sa.text(query),connection))

                                 product_name  quantity_product_sold
0  Global Push Button Manager's Chair, Indigo                   22.0

In [ ]:
# 11. Which customer got the most discount in the data? (in total amount)
query = """
SELECT
    o.customer_id,
    c.customer_name,
    ROUND(CAST(SUM((od.order_sales / (1 - od.order_discount)) - od.order_sales) AS NUMERIC), 2) AS total_discount
FROM
    orders o
JOIN
    order_details od ON o.order_id = od.order_id
JOIN
    customers c ON o.customer_id = c.customer_id
GROUP BY
    o.customer_id, c.customer_name
ORDER BY
    total_discount DESC
LIMIT 1;
"""

display(pd.read_sql(sa.text(query),connection))

   customer_id customer_name  total_discount
0          687   Sean Miller        23929.08

In [ ]:
# 12. How widely did monthly profits vary in 2018?
query = """
with months_total AS (
  SELECT TO_CHAR(order_date, 'MM-YYYY') AS month,
  SUM(order_profits) AS month_total
  FROM orders JOIN order_details USING(order_id)
  WHERE EXTRACT(YEAR FROM order_date) = 2018
  GROUP BY TO_CHAR(order_date, 'MM-YYYY')
  )


  SELECT month,
  month_total,
  month_total - LAG(month_total) OVER(ORDER BY month) AS month_diff
  FROM months_total;

"""

display(pd.read_sql(sa.text(query),connection))

      month  month_total  month_diff
0   01-2018       7137.0         NaN
1   02-2018       1612.0     -5525.0
2   03-2018      14758.0     13146.0
3   04-2018        934.0    -13824.0
4   05-2018       6342.0      5408.0
5   06-2018       8226.0      1884.0
6   07-2018       6951.0     -1275.0
7   08-2018       9034.0      2083.0
8   09-2018      10987.0      1953.0
9   10-2018       9272.0     -1715.0
10  11-2018       9217.0       -55.0
11  12-2018       8473.0      -744.0

In [ ]:
# 13. Which was the biggest order regarding sales in 2015?
query = """
SELECT order_id, SUM(order_sales) AS total_order_sales
FROM order_details
LEFT JOIN orders
USING(order_id)
WHERE EXTRACT(YEAR FROM shipping_date)=2015
GROUP BY order_id
ORDER BY total_order_sales DESC
LIMIT 1
"""

display(pd.read_sql(sa.text(query),connection))

         order_id  total_order_sales
0  CA-2015-145317            23660.0

In [ ]:
# 14. What was the rank of each city in the East region in 2015 in quantity?
query = """
SELECT
    o.shipping_city,
    SUM(od.quantity) AS total_quantity,
    RANK() OVER (ORDER BY SUM(od.quantity) DESC) AS rank
FROM
    orders o
JOIN
    order_details od ON o.order_id = od.order_id
WHERE
    o.shipping_region = 'East' AND
    EXTRACT(YEAR FROM o.order_date) = 2015
GROUP BY
    o.shipping_city
ORDER BY
    rank;
"""

display(pd.read_sql(sa.text(query),connection))

    shipping_city  total_quantity  rank
0   New York City          1708.0     1
1    Philadelphia           403.0     2
2        Columbus           167.0     3
3          Newark            64.0     4
4       Fairfield            53.0     5
5      Long Beach            44.0     6
6        Lakewood            38.0     7
7       Lancaster            36.0     8
8        Lawrence            31.0     9
9           Dover            30.0    10
10     Hackensack            28.0    11
11         Bangor            24.0    12
12          Utica            24.0    12
13         Lowell            23.0    14
14        Yonkers            22.0    15
15     Wilmington            21.0    16
16        Clinton            20.0    17
17      Baltimore            20.0    17
18       Cranston            20.0    17
19        Everett            19.0    20
20     Providence            19.0    20
21        Buffalo            19.0    20
22         Medina            16.0    23
23        Meriden            15.0    24
24        Beverly            15.0    24
25   New Rochelle            14.0    26
26        Bristol            14.0    26
27      Hempstead            12.0    28
28      Cleveland            12.0    28
29      Rochester            12.0    28
30         Toledo            12.0    28
31      Watertown            12.0    28
32        Chester            11.0    33
33           Troy            11.0    33
34       Franklin            11.0    33
35          Akron            10.0    36
36        Clifton             9.0    37
37      Jamestown             9.0    37
38        Concord             9.0    37
39       Columbia             8.0    40
40         Lorain             8.0    40
41       Hamilton             8.0    40
42     Cincinnati             8.0    40
43          Mason             7.0    44
44   Mount Vernon             7.0    44
45         Linden             7.0    44
46        Reading             6.0    47
47         Revere             6.0    47
48           Kent             5.0    49
49      Oceanside             5.0    49
50    Springfield             5.0    49
51         Orange             4.0    52
52          Parma             4.0    52
53  Niagara Falls             3.0    54
54     Plainfield             3.0    54
55         Marion             3.0    54
56  Bowling Green             2.0    57
57       Freeport             2.0    57
58     Middletown             2.0    57
59     Woonsocket             2.0    57

In [ ]:
# 15. Display customer names for customers who are in the segment ‘Consumer’ or ‘Corporate.’ How many customers are there in total?
query = """
SELECT customer_name,
COUNT(*) OVER() as total_number_customers
FROM customers
WHERE customer_segment IN ('Consumer', 'Corporate')
"""

display(pd.read_sql(sa.text(query),connection))

              customer_name  total_number_customers
0             Aaron Bergman                     647
1             Aaron Hawkins                     647
2            Aaron Smayling                     647
3                 Adam Hart                     647
4        Adam Shillingsburg                     647
5             Adrian Barton                     647
6               Aimee Bixby                     647
7               Alan Barnes                     647
8               Alan Haines                     647
9                Alan Hwang                     647
10        Alan Schoenberger                     647
11             Alan Shonely                     647
12          Alejandro Grove                     647
13         Alejandro Savely                     647
14      Aleksandra Gannaway                     647
15               Alex Avila                     647
16             Alex Grayson                     647
17             Alex Russell                     647
18           Alice McCarthy                     647
19             Allen Armold                     647
20           Allen Goldenen                     647
21         Allen Rosenblatt                     647
22            Alyssa Crouse                     647
23                  Amy Cox                     647
24                 Amy Hunt                     647
25             Andrew Allen                     647
26          Andrew Gjertsen                     647
27           Andrew Roberts                     647
28             Andy Gerbode                     647
29              Andy Reiter                     647
30               Andy Yotov                     647
31           Anemone Ratner                     647
32              Angele Hood                     647
33                Ann Blume                     647
34                Ann Chong                     647
35            Anna Andreadi                     647
36               Anna Chung                     647
37              Anna Gayman                     647
38            Anna Häberlin                     647
39           Anne McFarland                     647
40            Annie Thurman                     647
41             Annie Zypern                     647
42           Anthony Jacobs                     647
43          Anthony Johnson                     647
44        Anthony O'Donnell                     647
45           Anthony Rawles                     647
46             Anthony Witt                     647
47           Arianne Irving                     647
48             Art Ferguson                     647
49               Art Foster                     647
50            Arthur Gainer                     647
51           Arthur Prichep                     647
52            Ashley Jarboe                     647
53             Astrea Jones                     647
54           Barbara Fisher                     647
55          Barry Blumstein                     647
56        Barry Französisch                     647
57           Barry Gonzalez                     647
58               Barry Pond                     647
59            Barry Weirich                     647
60                Bart Folk                     647
61             Bart Pistole                     647
62             Bart Watters                     647
63             Becky Martin                     647
64                Becky Pak                     647
65             Ben Peterman                     647
66              Ben Wallace                     647
67       Benjamin Patterson                     647
68          Benjamin Venier                     647
69           Berenike Kampe                     647
70            Beth Fritzler                     647
71               Beth Paige                     647
72           Bill Donatelli                     647
73            Bill Overfelt                     647
74             Bill Shonely                     647
75             Bill Stewart                     647
76               Bill Tyler                     647
77              Bobby Elias                     647
78            Bobby Odegard                     647
79            Bobby Trafton                     647
80             Brad Norvell                     647
81          Bradley Drucker                     647
82           Bradley Nguyen                     647
83            Brenda Bowman                     647
84            Brendan Murry                     647
85            Brendan Sweed                     647
86             Brian Dahlen                     647
87          Brian DeCherney                     647
88               Brian Derr                     647
89               Brian Moss                     647
90            Brian Stugart                     647
91           Brian Thompson                     647
92        Brooke Gillingham                     647
93          Brosina Hoffman                     647
94         Bruce Degenhardt                     647
95               Bruce Geld                     647
96            Bruce Stewart                     647
97              Bryan Davis                     647
98              Bryan Mills                     647
99          Candace McMahon                     647
100              Cari Sayre                     647
101         Cari Schnelling                     647
102            Carl Jackson                     647
103             Carl Ludwig                     647
104             Carlos Daly                     647
105           Carlos Meador                     647
106          Carlos Soltero                     647
107             Carol Adams                     647
108            Carol Darley                     647
109            Carol Triggs                     647
110         Caroline Jumper                     647
111       Cassandra Brandow                     647
112          Cathy Prescott                     647
113            Chad McGuire                     647
114            Chad Sievert                     647
115        Charles Crestani                     647
116       Charles McCrossin                     647
117         Charles Sheldon                     647
118        Charlotte Melton                     647
119     Chloris Kastensmidt                     647
120            Chris Cortes                     647
121            Chris McAfee                     647
122         Chris Selesnick                     647
123      Christina Anderson                     647
124        Christina DeMoss                     647
125  Christina VanderZanden                     647
126       Christine Abelman                     647
127          Christine Phan                     647
128    Christine Sundaresam                     647
129      Christopher Conant                     647
130    Christopher Martinez                     647
131        Christy Brittain                     647
132             Chuck Magee                     647
133             Chuck Sachs                     647
134           Cindy Chapman                     647
135        Cindy Schnelling                     647
136           Cindy Stewart                     647
137             Claire Gute                     647
138        Claudia Bergmann                     647
139           Clay Cheatham                     647
140             Clay Ludtke                     647
141            Clytie Kelty                     647
142           Corey Catlett                     647
143              Corey-Lock                     647
144          Craig Carreira                     647
145           Craig Carroll                     647
146          Craig Molinari                     647
147            Craig Reiter                     647
148            Craig Yedwab                     647
149             Cyma Kinney                     647
150         Cynthia Arntzen                     647
151           Cynthia Voltz                     647
152         Damala Kotsonis                     647
153            Dan Campbell                     647
154              Dan Lawera                     647
155         Dan Reichenbach                     647
156             Dana Kaydos                     647
157             Daniel Lacy                     647
158            Dario Medina                     647
159             Darren Budd                     647
160          Darren Koutras                     647
161           Darren Powers                     647
162           Darrin Martin                     647
163         Darrin Van Huff                     647
164             Dave Brooks                     647
165           Dave Hallsten                     647
166               Dave Kipp                     647
167            Dave Poirier                     647
168            David Bremer                     647
169          David Flashing                     647
170          David Kendrick                     647
171          David Philippe                     647
172             David Smith                     647
173            David Wiener                     647
174             Dean Braden                     647
175               Dean Katz                     647
176            Debra Catini                     647
177           Deirdre Greer                     647
178       Delfina Latchford                     647
179       Denise Leinenbach                     647
180           Denise Monton                     647
181             Dennis Kane                     647
182           Denny Blanton                     647
183               Denny Joy                     647
184            Denny Ordway                     647
185        Dianna Vittorini                     647
186            Dionis Lloyd                     647
187               Don Jones                     647
188              Don Miller                     647
189               Don Weiss                     647
190         Dorothy Badders                     647
191       Dorothy Dickinson                     647
192          Dorothy Wardle                     647
193            Dorris liebe                     647
194           Doug Bickford                     647
195             Doug Jacobs                     647
196          Doug O'Connell                     647
197            Duane Benoit                     647
198            Duane Noonan                     647
199              Ed Braxton                     647
200               Ed Jacobs                     647
201           Edward Becker                     647
202            Edward Hooks                     647
203           Edward Nazzal                     647
204           Eleni McCrary                     647
205       Elizabeth Moffitt                     647
206           Ellis Ballard                     647
207       Elpida Rittenbach                     647
208             Emily Burns                     647
209             Emily Grady                     647
210              Emily Phan                     647
211            Eric Barreto                     647
212           Eric Hoffmann                     647
213            Eric Murdock                     647
214              Erica Bern                     647
215           Erica Hackney                     647
216             Erica Smith                     647
217           Erin Ashbrook                     647
218          Erin Creighton                     647
219               Erin Mull                     647
220              Erin Smith                     647
221          Eudokia Martin                     647
222          Eugene Barchas                     647
223              Eva Jacobs                     647
224           Evan Bailliet                     647
225              Evan Henry                     647
226           Filia McAdams                     647
227          Frank Atkinson                     647
228            Frank Hawley                     647
229             Frank Olsen                     647
230             Frank Preis                     647
231              Fred Chung                     647
232             Fred Harton                     647
233            Fred Hopkins                     647
234             Fred McMath                     647
235          Fred Wasserman                     647
236              Gary Hwang                     647
237             Gary McGarr                     647
238           Gary Zandusky                     647
239               Gene Hale                     647
240            Gene McClure                     647
241         George Ashbrook                     647
242             George Bell                     647
243         George Zrebassa                     647
244       Georgia Rosenberg                     647
245       Giulietta Baptist                     647
246        Giulietta Dortch                     647
247        Giulietta Weimer                     647
248             Grace Kelly                     647
249          Grant Thornton                     647
250            Greg Guthrie                     647
251             Greg Hansen                     647
252           Greg Matthias                     647
253            Greg Maxwell                     647
254               Greg Tran                     647
255           Guy Armstrong                     647
256             Guy Phonely                     647
257            Guy Thornton                     647
258            Harold Engle                     647
259             Harold Ryan                     647
260            Harry Greene                     647
261             Harry Marie                     647
262        Heather Kirkland                     647
263           Helen Abelman                     647
264          Helen Andreada                     647
265         Helen Wasserman                     647
266             Henia Zydlo                     647
267           Henry Goldwyn                     647
268       Henry MacAllister                     647
269         Herbert Flentye                     647
270           Hilary Holden                     647
271           Hunter Glantz                     647
272            Hunter Lopez                     647
273           Ionia McGrath                     647
274            Irene Maddox                     647
275             Ivan Gibson                     647
276             Ivan Liston                     647
277              Jack Garza                     647
278             Jack Lebron                     647
279           Jack O'Briant                     647
280            James Galang                     647
281            Jamie Frazer                     647
282            Jamie Kunitz                     647
283               Jane Waco                     647
284               Janet Lee                     647
285            Janet Martin                     647
286          Janet Molinari                     647
287           Jas O'Carroll                     647
288          Jason Fortune-                     647
289             Jason Gross                     647
290       Jason Klamczynski                     647
291         Jasper Cacioppo                     647
292                Jay Fein                     647
293              Jay Kimmel                     647
294            Jenna Caffey                     647
295        Jennifer Braxton                     647
296       Jennifer Ferguson                     647
297       Jennifer Halladay                     647
298        Jennifer Jackson                     647
299           Jennifer Patt                     647
300          Jeremy Ellison                     647
301            Jeremy Farry                     647
302         Jeremy Lonsdale                     647
303           Jeremy Pistek                     647
304          Jessica Myrick                     647
305              Jill Fjeld                     647
306           Jill Matthias                     647
307          Jill Stevenson                     647
308                 Jim Epp                     647
309            Jim Karlsson                     647
310             Jim Mitchum                     647
311             Jim Radford                     647
312                Jim Sink                     647
313          Jocasta Rupert                     647
314              Joe Elijah                     647
315           Joe Kamberova                     647
316              Joel Eaton                     647
317            John Castell                     647
318              John Dryer                     647
319              John Grady                     647
320             John Huston                     647
321                John Lee                     647
322              John Lucas                     647
323             John Murray                     647
324          John Stevenson                     647
325        Jonathan Doherty                     647
326         Jonathan Howell                     647
327          Joni Blumstein                     647
328          Joni Wasserman                     647
329            Joseph Airdo                     647
330             Joseph Holt                     647
331               Joy Bell-                     647
332             Joy Daniels                     647
333               Joy Smith                     647
334            Julia Dunbar                     647
335              Julia West                     647
336           Juliana Krohn                     647
337         Julie Creighton                     647
338        Justin Deggeller                     647
339          Justin Ellison                     647
340            Justin Hirsh                     647
341      Justin MacKendrick                     647
342           Justin Ritter                     647
343            Kalyca Meade                     647
344              Karen Bern                     647
345          Karen Carlisle                     647
346           Karen Daniels                     647
347              Karen Seio                     647
348              Karl Braun                     647
349         Katharine Harms                     647
350        Katherine Ducich                     647
351        Katherine Hughes                     647
352       Katherine Nockton                     647
353         Katrina Edelman                     647
354         Katrina Willman                     647
355             Kean Nguyen                     647
356           Kean Takahito                     647
357           Kean Thornton                     647
358           Keith Dawkins                     647
359           Keith Herrera                     647
360          Kelly Andreada                     647
361         Kelly Collister                     647
362           Kelly Lampkin                     647
363          Kelly Williams                     647
364               Ken Black                     647
365             Ken Brennan                     647
366                Ken Dana                     647
367              Ken Heidel                     647
368            Ken Lonsdale                     647
369            Khloe Miller                     647
370         Kimberly Carter                     647
371        Kristen Hastings                     647
372            Kunst Miller                     647
373            Larry Blacks                     647
374            Larry Hughes                     647
375              Larry Tron                     647
376         Laura Armstrong                     647
377         Laurel Elliston                     647
378          Laurel Workman                     647
379      Lauren Leatherbury                     647
380            Lela Donovan                     647
381           Lena Cacioppo                     647
382          Lena Creighton                     647

In [ ]:
# 16. Calculate the difference between the largest and smallest order quantities for product id ‘100.’

query = """
SELECT MAX(quantity)-MIN(quantity) AS difference_order_quantities
FROM order_details
WHERE product_id=100

"""

display(pd.read_sql(sa.text(query),connection))

   difference_order_quantities
0                            4

In [ ]:
# 17. Calculate the percent of products that are within the category ‘Furniture.’
query = """
SELECT
    ROUND(
        (COUNT(CASE WHEN product_category = 'Furniture' THEN 1 END) * 100.0) / COUNT(*), 2
    ) AS furniture_percent
FROM
    product
"""

display(pd.read_sql(sa.text(query),connection))

   furniture_percent
0              20.54

In [ ]:
# 18. Display the number of product manufacturers with more than 1 product in the product table.
query = """
SELECT product_manufacturer, COUNT(DISTINCT product_id) AS num_of_duplicates
FROM product
GROUP BY product_manufacturer
HAVING COUNT(DISTINCT product_id) > 1
ORDER BY COUNT(DISTINCT product_id)
"""

display(pd.read_sql(sa.text(query),connection))

      product_manufacturer  num_of_duplicates
0             Things To Do                  2
1        Texas Instruments                  2
2           Gould Plastics                  2
3                 Euro Pro                  2
4                    G. E.                  2
5               First Data                  2
6                Stockwell                  2
7                Sterilite                  2
8                     Akro                  2
9                  Stanley                  2
10                Standard                  2
11                 Angle-D                  2
12                  Square                  2
13                   Sharp                  2
14                   Array                  2
15                  iOttie                  2
16                   Sanyo                  2
17                  Avanti                  2
18                    Rush                  2
19                 Quartet                  2
20                    Pyle                  2
21              3D Systems                  2
22                Barricks                  2
23                 Premier                  2
24                    Poly                  2
25             Peel & Seel                  2
26                Bionaire                  2
27      Office Impressions                  2
28                   Mitel                  2
29                 Brother                  2
30                 Bulldog                  2
31       Micro Innovations                  2
32             Martin-Yale                  2
33                  Linden                  2
34                   Lesro                  2
35                      KI                  2
36                 Jawbone                  2
37                    Iris                  2
38                ClearOne                  2
39             Clearsounds                  2
40                 Crayola                  2
41                  Cubify                  2
42                 Harmony                  2
43                     DMI                  2
44                     DXL                  2
45                XtraLife                  2
46                Decoflex                  2
47               Hammermil                  2
48                     HTC                  2
49                 Griffin                  2
50             Grandstream                  2
51                    Balt                  3
52                ACCOHIDE                  3
53                   Ativa                  3
54                    Dana                  3
55                 Enermax                  3
56                   Epson                  3
57                 Iceberg                  3
58                      LG                  3
59            Message Book                  3
60                 NETGEAR                  3
61                   Nokia                  3
62                   Prang                  3
63                   Razer                  3
64               Riverside                  3
65                   Smead                  3
66         Space Solutions                  3
67                  Storex                  3
68              Strathmore                  3
69              Tripp Lite                  3
70          WD My Passport                  3
71            Westinghouse                  3
72                OtterBox                  4
73                   Avaya                  4
74                Atlantic                  4
75                      HP                  4
76                   Jabra                  4
77                  Carina                  4
78               KeyTronic                  4
79                Kingston                  4
80                 Lexmark                  4
81                  C-Line                  4
82           Master Caster                  4
83                 Fiskars                  4
84                  Tensor                  4
85                Bretford                  4
86                   Tyvek                  4
87                   Ultra                  4
88                  Nortel                  4
89                 Novimex                  4
90                Alliance                  4
91                  Rogers                  4
92                    Hunt                  4
93              Pressboard                  4
94                   Apple                  4
95                   Zebra                  4
96          Binney & Smith                  5
97               Microsoft                  5
98                     RCA                  5
99               Universal                  5
100               REDIFORM                  5
101                Nu-Dell                  5
102              Honeywell                  5
103                    OIC                  5
104                    BIC                  5
105                  Ampad                  5
106               Electrix                  5
107                   Luxo                  5
108               Verbatim                  5
109                Okidata                  6
110                     3M                  6
111             Chromcraft                  6
112            Seth Thomas                  6
113                  Anker                  6
114               Motorola                  6
115                     GE                  7
116                   Sony                  7
117                Polycom                  7
118                   TOPS                  7
119                SanDisk                  8
120              Deflect-o                  8
121                 Eureka                  8
122                 Holmes                  8
123             Southworth                  8
124               Cardinal                  8
125                  Adams                  9
126                  Dixon                  9
127                  Canon                 10
128                 Hoover                 10
129                Samsung                 11
130                Imation                 11
131             Kensington                 11
132                   AT&T                 11
133                  Bevis                 11
134                Sanford                 11
135                 Sauder                 11
136              Wirebound                 11
137                Tennsco                 11
138        Hewlett-Packard                 11
139                  Ibico                 12
140                 Maxell                 12
141  Executive Impressions                 12
142            Office Star                 12
143          Howard Miller                 12
144                   Bush                 13
145               Advantus                 13
146             O'Sullivan                 13
147                Memorex                 13
148            Plantronics                 15
149                  Tenex                 16
150                  Cisco                 17
151                    DAX                 17
152              Panasonic                 18
153                 Boston                 18
154                   Acme                 19
155                  SAFCO                 20
156           Wilson Jones                 23
157                 Belkin                 25
158                    Hon                 33
159                   Acco                 34
160               Fellowes                 35
161               Logitech                 36
162                 Global                 40
163                    GBC                 45
164                  Eldon                 48
165                 Newell                 52
166                  Avery                 98
167                  Xerox                173
168                  Other                356

In [ ]:
# 19. Show the product_subcategory and the total number of products in the subcategory.
      #Show the order for the most to least number of products.
query = """
SELECT product_subcategory, COUNT(product_name) AS num_product_subcategory
FROM product
GROUP BY product_subcategory
ORDER BY num_product_subcategory DESC
"""

display(pd.read_sql(sa.text(query),connection))

   product_subcategory  num_product_subcategory
0                Paper                      277
1              Binders                      211
2               Phones                      189
3          Furnishings                      186
4                  Art                      157
5          Accessories                      147
6              Storage                      132
7           Appliances                       97
8               Chairs                       88
9               Labels                       70
10            Machines                       63
11              Tables                       56
12           Bookcases                       50
13           Envelopes                       44
14            Supplies                       36
15           Fasteners                       34
16             Copiers                       13

In [ ]:
# 20. Show the product_id(s), the sum of quantities, where for each sale of product quantities is greater than or equal to 100.
query = """
SELECT
    product_id,
    SUM(quantity) AS total_quantity
FROM
    order_details
WHERE
    quantity >= 100
GROUP BY
    product_id
ORDER BY
    total_quantity DESC;
"""

display(pd.read_sql(sa.text(query),connection))

   product_id  total_quantity
0        1507           324.0
1        1600           216.0
2         122           143.0
3         920           130.0